### ISSUE TITLE
macOS install instructions

### ISSUE THREAD

**Issue by cfurrow** [denq04/denq04.github.io#1]
Installing on macOS is a bit different than Windows, and I wanted to help add those instructions to your website.

# Steam Instructions on macOS

## Copying NCMS.dll

1. Open Finder and press Command+Shift+G
2. Type (or paste) in `~/Library/Application Support/Steam/steamapps/common/worldbox/worldbox.app/Contents/Resources/Data/StreamingAssets/Mods`
3. Copy NCMS.dll to that folder

Now run Worldbox and wait for it to finish loading up a new world. Press "M" or click on the "NCMS" mods button in your Worldbox toolbar (where you select your powers, etc).

If you can open the mods window, it worked!

## Installing mods
1. Open Finder and press Command+Shift+G
2. Type (or paste) in `~/Library/Application Support/Steam/steamapps/common/worldbox`
    1. _Note: you can also get to this folder from the Steam app. Right click on "Worldbox - God Simulator", select "Manage", then "Browse local files". That will open up the same path in Finder._
3. You should see a "Mods" folder and "worldbox.app"
4. Open the "Mods" folder
5. Copy your mods (e.g. "powerbox.mod", or whatever) into this "Mods" folder
6. Open up WorldBox again and your mods should be installed

**Comment by denq04** [comment]
Thank you, i will update it later

**Comment by denq04** [comment]
Wait, you sure about default mods folder path? `worldbox/worldbox.app/Contents/Resources/Data/StreamingAssets/Mods`? Because looks like it should be  `worldbox/Contents/Resources/Data/StreamingAssets/Mods`, i am not sure

**Comment by cfurrow** [comment]
I am sure, because that's how it ended up working for me.

DLL went into: `~/Library/Application Support/Steam/steamapps/common/worldbox/worldbox.app/Contents/Resources/Data/StreamingAssets/Mods`

But the mods would not work until I put them in `~/Library/Application Support/Steam/steamapps/common/worldbox/Mods`

**Comment by cfurrow** [comment]
I went to double check, and now my mods are gone. That may have happened due to the recent Worldbox update. Not sure why it would empty my Mods folder, but it's empty now. NCMS.dll is still in the "other" Mods folder, but the installed mods I had (Powerbox) are gone.

So now I'm less sure than I was previously 😟 

![CleanShot 2022-01-21 at 17 20 26@2x](https://user-images.githubusercontent.com/149965/150607838-9086e123-fd06-492b-8e28-bbc2002bdf82.png)

![CleanShot 2022-01-21 at 17 21 27@2x](https://user-images.githubusercontent.com/149965/150607939-31e55bdb-3d35-4bfb-9dda-383f74f5775d.png)

**Comment by denq04** [comment]
I am not sure about mac, how to open app files?

**Comment by cfurrow** [comment]
well, the mods are actually still there, but not showing up in my file browser. So I went to terminal and found they are still where I put them before.

![CleanShot 2022-01-21 at 17 27 21@2x](https://user-images.githubusercontent.com/149965/150608515-52515e96-d29c-46f4-9561-33f8803a6d84.png)

**Comment by cfurrow** [comment]
To open an ".app" file, you right click it and select "Show Package Contents"

<img width="318" alt="CleanShot 2022-01-21 at 17 29 11@2x" src="https://user-images.githubusercontent.com/149965/150608603-5b80ef7d-6b16-4d2d-96ad-aaca4b97d974.png">

**Comment by cfurrow** [comment]
Re-reading your question:
> Wait, you sure about default mods folder path? worldbox/worldbox.app/Contents/Resources/Data/StreamingAssets/Mods? > Because looks like it should be worldbox/Contents/Resources/Data/StreamingAssets/Mods, i am not sure

I think you mistook my original post. You are correct. 
DLL goes in to `worldbox/worldbox.app/Contents/Resources/Data/StreamingAssets/Mods`

and mods go into `worldbox/Contents/Resources/Data/StreamingAssets/Mods`

So you are correct, maybe we had a misunderstanding in the original description.

**Comment by denq04** [comment]
No, i meant people cant understand how they can go into `worldbox.app`, and i cant explain, because i am not mac user

**Comment by denq04** [comment]
and i cant explain, because i am not mac user

**Comment by denq04** [comment]
oh, i see, thanks

**Comment by cfurrow** [comment]
> people cant understand how they can go into worldbox.app

And that's why I wrote this in my instructions above:  Command+Shift+G

That opens up a window and lets you paste in a path. So, open Finder.app, then press Command+Shift+G, then paste in the paths I put in the original description. That will take you right to where you need to go. I gave all the instructions there because I assume some users would not know how to do that. So I was explicit.

**Comment by Prapraebosnewmers** [comment]
where can I download NCMS.dll
